// packages/qwik/src/root.tsx
import { Toaster, toast } from "./components";

export default () => {
  return (
    <>
      <head>
        <meta charSet="utf-8" />
        <title>Qwik Blank App</title>
      </head>
      <body
        style={{
          fontFamily:
            "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji;",
          minHeight: "100vh",
        }}
      >
        <button onClick$={() => toast.success("Prueba")}>Add toast</button>
        <Toaster richColors />
      </body>
    </>
  );
};

// src/root.tsx
import { $ } from "@builder.io/qwik";
import { Toaster, toast } from "./components";

export default () => {
  return (
    <>
      <head>
        <meta charSet="utf-8" />
        <title>Qwik Blank App</title>
      </head>
      <body>
        <button onClick$={() => toast.info("I'm a toast. Look at me")}>
          open toaster
        </button>
        <button onClick$={() => toast(<div>My custom toast</div>)}>
          open toaster 2
        </button>
        <button
          onClick$={() =>
            toast("Event has been created", {
              onDismiss: $((t) =>
                console.log(`Toast with id ${t.id} has been dismissed`)
              ),
              onAutoClose: $((t) =>
                console.log(
                  `Toast with id ${t.id} has been closed automatically`
                )
              ),
            })
          }
        >
          open toaster 3
        </button>
        <Toaster />
      </body>
    </>
  );
};
